/**:
  ros__parameters:
    K: [ -1.414214, -4.610230, -103.328731, -13.158521]

    ke: 0.0001
    kv: 1.0
    kx: 1000.0
    kdelta: 0.0001

    # 0.0 angle - upward position. When absolute angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.523599
    initial_force: 30.0
    rviz_test: true
